### ISSUE TITLE
Missing Namespace qualifier in LinearSolver.C

### ISSUE THREAD

**Issue by crtrott** [spdomin/Nalu#11]
There are a few instances of Teuchos:: missing in front of "Time" and "TimeMonitor" in LinearSolver.C. This did not show up when using KokkosClassic but does when using the new Kokkos backend for Tpetra. My guess is that somehwere Teuchos::Time[Monitor] gets imported  or marked with "using" and that file is not included when building with the new Kokkos backend.

Lines: 157,270,272

**Comment by spdomin** [comment]
This has been resolved: https://github.com/spdomin/Nalu/commit/ebdf29b08fdeccdbaa294c016a340e6cb74f42d3
