### ISSUE TITLE
Timers are inconsistent (revert to wall_time)

### ISSUE THREAD

**Issue by crtrott** [spdomin/Nalu#41]
In march the timers were changed to stk::cpu_time from stk::wall_time. That means that now the actual wall time is multiplied by the number of threads the process is using (or rather the number of cycles all threads together consume). While this can be a useful measure to get the total consumed hardware resources, I don't think that is what was intended. In particular you would need accumulate MPI time as well instead of providing min, ave and max. Otherwise in a perfect threaded code the time reported by NALU goes up when you use more threads and less MPI ranks, even though the wall clock time is the same.

**Comment by nmhamster** [comment]
@spdomin this is becoming quite a problem for our system assessment and benchmarking activities. Is there any chance that we can get this switched over soon please?

**Comment by spdomin** [comment]
I am more concerned with making sure that we can keep a passing test suite. Let's focus on that first.

**Comment by nmhamster** [comment]
@spdomin I don't disagree with that but .. we have a huge amount of work resting on these timer outputs for acceptance, several L2 reports etc. We are having to manually modify builds to ensure our hardware evaluations are coming out with sensible results. Once we are over the L2 etc then I'm happy to devote a lot of time to the Trilinos problems.

**Comment by spdomin** [comment]
Okay, I had no idea that this was so painful for you.

However, internal Nalu timers **always** used cpu_time, e.g., a code snippet from v1.0-release shows the following:

time += stk::cpu_time();
timerAdapt_ += time;

Are you sure that you do not mean that STK changed its' timer? 

Specifically, 

stk::diag::TimeBlock tbComputeGeom_(timerComputeGeom_);
compute_geometry();

I think that we will need to ask the STK team about this. Have you asked them yet?

Finally, in my output, I see the following Nalu timer overview, which as I proved has always been cpu_time:

Timing for Eq: MomentumEQS
             init --    avg: 0.375893   min: 0.375552   max: 0.376233

and the timers from STK - which include both CPU and wall time...

                                                     CPU Time              CPU Time              CPU Time              Wall Time             Wall Time             Wall Time
                 Timer                   Count   Sum (% of System)     Min (% of System)     Max (% of System)     Sum (% of System)     Min (% of System)     Max (% of System)
---------------------------------------- ----- --------------------- --------------------- --------------------- --------------------- --------------------- ---------------------
Nalu                                         2       33.191 (100.0%)       16.594 (50.00%)       16.597 (50.00%)       30.873 (100.0%)       15.436 (50.00%)       15.437 (50.00%)

Argh... I guess I am back where I was when C submitted the issue - sorely confused. However, this time I will not drop it and work towards a solution.

Please comment on the above and we can chat at your earliest convenience.

**Comment by nmhamster** [comment]
CPU time was fine before you had threaded code (like Trilinos). Once threads are enabled CPU time includes all the time for threads including busy wait, we just want wall time for sections we care about. It's good for serial although includes some MPI profiling overhead. Does that help?

**Comment by spdomin** [comment]
Okay, I looked for the change that C suggested and it never happened. Nalu has always reported CPU time for its internal timers. 

However, obviously, the underlying argument is still valid despite the incorrect conclusion that we changed the code. In fact, the only code change related to timers in the recent past was the ability to force an output after a certain amount of wall time occurred.

If you can, please comment on the assertion that Nalu changed its timers and I can start working on the change to use wall_time given the highly logical arguments.

**Comment by nmhamster** [comment]
@spdomin - ok this is complicated if the regions contain MPI because CPU time may or may not count these. What we want is really CPU time / threads for OpenMP CPU code but something different from GPU. Any chance you can create your own timer function that we can modify on a per platform basis? Default would be STK wall time?

**Comment by spdomin** [comment]
If anything, I would convert to using only stk::timers through Diag:)

Let's connect tomorrow at work. Again, I was originally thrown by the ticket title based on the assertion that Nalu changed its timers. I read that and said, "hmm, we never used wall_time, he must be mistaken". 

Now that we are all on the same page, we can talk about a solution in Nalu to provide you with what you want. If you prototype the method, I can push it.

**Comment by nmhamster** [comment]
@spdomin sure, I'll be back from CA around 1, few meetings. I'll try call you. Thank you!

**Comment by spdomin** [comment]
Okay, added NaluEnv::nalu_time() used as follows:

time += NaluEnv::self().nalu_time();

with 

double
NaluEnv::nalu_time()
{
  return stk::wall_time();
}

Look okay? I am testing now...

**Comment by spdomin** [comment]
Done.. 

commit 0da09d63a6af26952874d0fa9ad5743ba28d60d4

Please confirm and I can close:) Sorry for the delay. In time, we can add ifdefs based on platforms.
