### ISSUE TITLE
Nalu should use Tpetra::Vector::update instead of rolling loop by hand

### ISSUE THREAD

**Issue by mhoemmen** [spdomin/Nalu#69]
Lines 165-168 here:

https://github.com/spdomin/Nalu/blob/ae129dd8041a82a0188efbaa044d0bf62ca91ded/src/LinearSolver.C#L165

are an inefficient reimplementation of existing Tpetra functionality.  Do this instead:
```
resid.update (-1.0, *rhs_, 1.0); 
```
That line replaces Lines 165-168. 
```

**Comment by spdomin** [comment]
Many thanks, @mhoemmen. @alanw0, could you have a look?

**Comment by alanw0** [comment]
Yes I'll take a look.

**Comment by alanw0** [comment]
ok this is done.

**Comment by spdomin** [comment]
https://github.com/NaluCFD/Nalu/commit/3c481a35864ad63fd147e93a1548bc47e8eb4430

**Comment by spdomin** [comment]
I just noticed that this was on the spdomin/Nalu code base. We have moved to NaluCFD... 

I could not understand why this issue was coming and going, however, finally realized that it was filed under spdomin/Nalu:)

Alan made the correct code change though...

**Comment by mhoemmen** [comment]
@spdomin Looks good to me!  Thanks :-D
