### ISSUE TITLE
It shows that yaml-cpp/yaml.h not found during make, but I can find the yaml.h for 100% sure

### ISSUE THREAD

**Issue by RogerSang** [spdomin/Nalu#71]
It shows that yaml-cpp/yaml.h not found during make, but I can find the yaml.h for 100% sure

Scanning dependencies of target nalu
[ 0%] Building CXX object CMakeFiles/nalu.dir/src/Adapter.C.o
[ 1%] Building CXX object CMakeFiles/nalu.dir/src/Algorithm.C.o
[ 1%] Building CXX object CMakeFiles/nalu.dir/src/AlgorithmDriver.C.o
[ 2%] Building CXX object CMakeFiles/nalu.dir/src/AssembleContinuityEdgeContactSolverAlgorithm.C.o
In file included from /home/zsl1990/nalu_build_dir/nalu/include/NaluParsing.h:12:0,
from /home/zsl1990/nalu_build_dir/nalu/include/EquationSystem.h:12,
from /home/zsl1990/nalu_build_dir/nalu/src/AssembleContinuityEdgeContactSolverAlgorithm.C:11:
/home/zsl1990/nalu_build_dir/nalu/include/BoundaryConditions.h:15:27: fatal error: yaml-cpp/yaml.h: No such file or directory
#include <yaml-cpp/yaml.h>
^
compilation terminated.
make[2]: *** [CMakeFiles/nalu.dir/src/AssembleContinuityEdgeContactSolverAlgorithm.C.o] Error 1
make[1]: *** [CMakeFiles/nalu.dir/all] Error 2
make: *** [all] Error 2

While I open the file in the install folder, I can very clearly find the yaml.h in the /home/zsl1990/install/yaml/include/yaml-cpp. So what's wrong with my installation, what should I do to deal with the problem. Thanks so much for your help!

**Comment by spdomin** [comment]
I just read this... Did you figure this out? This error is generally from a mismatch between YAML versions.

**Comment by RogerSang** [comment]
Dear Stefan Domino,

Thanks for your response! 

No, I am still trying to fix it up.. I used version yaml-cpp-0.3.0 as you wrote in https://github.com/spdomin/Nalu/wiki/linux_rh6 <https://github.com/spdomin/Nalu/wiki/linux_rh6>, but doesn’t work for me. It is really frustrated that stuck on the last installation step. Would you mind giving me some hints that which version should I use?

Thanks so much for your help and stay well!

Cheers,
Roger Sang

**Comment by RogerSang** [comment]
Dear Stefan Domino,

I tried the version 0.6.2 and my nalu version is hyperbolic_levelset. Still got the same YAML problem and would you mind giving me more detail about the version of yaml that I should install? Thanks so much for your time and stay well!

Cheers,
Roger Sang

**Comment by spdomin** [comment]
I would follow these instructions: https://nalu.readthedocs.io/en/latest/source/user/build_manually.html#linux-and-osx 

I should probably deprecate spdomin/Nalu and the instructions found here:  https://github.com/spdomin/Nalu/wiki/linux_rh6
